# Generated by Django 5.0.14 on 2026-06-21 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About SARHIE', max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'About Content',
                'verbose_name_plural': 'About Content',
            },
        ),
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(default='SARHIE', max_length=20)),
                ('tagline', models.CharField(default='The South Asia Research Hub for Inclusive Education', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('cta_primary_label', models.CharField(default='Learn More', max_length=100)),
                ('cta_primary_target', models.CharField(default='about', max_length=100)),
                ('cta_secondary_label', models.CharField(default='Meet the Team', max_length=100)),
                ('cta_secondary_target', models.CharField(default='team', max_length=100)),
            ],
            options={
                'verbose_name': 'Hero Content',
                'verbose_name_plural': 'Hero Content',
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=50)),
                ('icon_name', models.CharField(blank=True, help_text='MUI icon name (e.g. Groups, School, Public)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='api.aboutcontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
