services:
  - type: web
    name: sarhie-api
    runtime: python
    region: singapore
    plan: free
    rootDirectory: backend
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application --workers 2 --threads 4 --timeout 120 --access-logfile -
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: sarhie-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.0

databases:
  - name: sarhie-db
    region: singapore
    plan: free
    postgresMajorVersion: 16
